# -*- coding: utf-8 -*-
"""fastai_mnist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UTnRhQbN-ufAK4VkmfrTi1WmnLqDNEdP
"""

#hide
! pip install -Uqq fastbook
import fastbook
fastbook.setup_book()

from fastai.vision.all import *
from fastbook import *

path=untar_data(URLs.MNIST)

Path.BASE_PATH=path

path.ls()
(path/'training').ls()



model = nn.Sequential(
    nn.Conv2d(3,6,5),
    nn.ReLU(),
    nn.MaxPool2d(2),
    nn.Conv2d(6,16,5),
    nn.ReLU(),
    nn.MaxPool2d(2),
    Flatten(),
    nn.Linear(16*5*5,120),
    nn.ReLU(),
    nn.Linear(120,84),
    nn.ReLU(),
    nn.Linear(84,10),
)

Train=path/'training'
Train.ls()
Test=path/'testing'
Test.ls()
data = ImageDataLoaders.from_folder(Train,get_image_files(Train),valid_pct=0.2,seed=42,item_tfms=Resize(32))
learns=Learner(data,model,metrics=accuracy)
learns.fit_one_cycle(15)

plt.plot(L(learns.recorder.values).itemgot(2))

learns.show_results()




